name: Python CI/CD for Insurance Cost Prediction

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'  # Specify the Python version you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Ensure your dependencies are listed in requirements.txt

    - name: Run tests
      run: |
        pytest  # Replace with your test command, e.g., `pytest` for running tests

    - name: Build and Package
      run: |
        # Add any build or packaging commands if needed
        # For example, if you're using a setup.py script for packaging
        python setup.py sdist bdist_wheel

    - name: Upload package
      uses: actions/upload-artifact@v3
      with:
        name: insurance-cost-prediction-package
        path: dist/*.tar.gz  # Adjust path based on your build output

    - name: Deploy to Heroku
      if: github.event_name == 'push'
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://git.heroku.com/YOUR_APP_NAME.git
        git push heroku main

    - name: Notify Deployment
      if: github.event_name == 'push'
      run: |
        echo "Deployment successful!"
